const data = {
  products: [
    {
      // _id: '1',
      name: 'First Name',
      slug: 'first-name',
      category: 'first-category',
      image: '/images/p1.jpg',
      price: 100,
      countInStock: 10,
      brand: 'z-performance',
      rating: 0.5,
      numReviews: 10,
      description: 'Best rims on the entire planet',
    },
    {
      // _id: '2',
      name: 'Second Name',
      slug: 'second-name',
      category: 'first-category',
      image: '/images/p1.jpg',
      price: 100,
      countInStock: 0,
      brand: 'z-performance',
      rating: 5,
      numReviews: 10,
      description: 'Best rims on the entire planet',
    },
    {
      // _id: '3',
      name: 'Third Name',
      slug: 'third-name',
      category: 'second-category',
      image: '/images/p1.jpg',
      price: 100,
      countInStock: 10,
      brand: 'z-performance',
      rating: 5,
      numReviews: 10,
      description: 'Best rims on the entire planet',
    },
  ],
};

export default data;
